ProjectII/Controllers/ApplicantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectII.Models;
using ProjectII.ViewModels;

namespace ProjectII.Controllers
{
    [Authorize]
    public class ApplicantsController : Controller
    {
        private ProjectIIContext db = new ProjectIIContext();

        // GET: Applicants
        public ActionResult Index(string search, string type)
        {
            // instantiate a new view model
            ApplicantViewModel viewModel = new ApplicantViewModel();
            var applicants = (IQueryable<Applicant>)db.Applicants;

            if (!String.IsNullOrEmpty(search))
            {
                switch (type)
                {
                    case "SSN":
                        applicants = applicants.Where(a => a.SSN.Contains(search));
                        break;
                    case "LastName":
                        applicants = applicants.Where(a => a.LastName.Contains(search));
                        break;
                }
                viewModel.search = search;
                viewModel.type = type;
            }

            viewModel.Applicants = applicants.OrderByDescending(a => a.ApplicationDate);

            if (Request.IsAjaxRequest())
            {
                return PartialView("ApplicantsPartial", viewModel);
            }

            return View(viewModel);
        }

        // GET: Applicants/Details/5
        [Route("applicant/{id}")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicant = db.Applicants.Find(id);

            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }

        // GET: Applicants/Create
        [AllowAnonymous]
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        // POST: Applicants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Create([Bind(Include = "ApplicantID,ApplicationDate,FirstName,MiddleName,LastName,SSN,EmailAddress,HomePhone,CellPhone,Street,City,State,Zipcode,DOB,Gender,HS,HSCity,GraduationDate,GPA,MathScore,VerbalScore,Major,EnrollmentTerm,EnrollmentYear,EnrollmentDecision")] Applicant applicant)
        {
            if (ModelState.IsValid)
            {
                var rejected = false;
                Applicant DuplicateApplicant = db.Applicants.Where(cm => string.Compare(cm.SSN, applicant.SSN, true) == 0).FirstOrDefault();

                if (DuplicateApplicant != null)
                {
                    ModelState.AddModelError("", "The applicant has already applied.");
                    return View(applicant);
                }

                if (applicant.GPA < Constants.minGPA || applicant.MathScore + applicant.VerbalScore < Constants.minScore)
                {
                    applicant.EnrollmentDecision = "Reject";
                    rejected = true;
                }

                db.Applicants.Add(applicant);
                db.SaveChanges();

                if (rejected)
                {
                    return RedirectToAction("Rejected");
                }
                return RedirectToAction("Success", new { id = applicant.ApplicantID });
            }
            return View(applicant);
        }

        // GET: Applicants/Rejection/5
        [AllowAnonymous]
        [Route("application-rejected")]
        public ActionResult Rejected()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: Applicants/Success/5
        [AllowAnonymous]
        [Route("application/{id}")]
        public ActionResult Success(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Applicant applicant = db.Applicants.Find(id);

            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }

        // GET: Applicants/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Applicant applicant = db.Applicants.Find(id);

            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }

        // POST: Applicants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicantID,ApplicationDate,FirstName,MiddleName,LastName,SSN,EmailAddress,HomePhone,CellPhone,Street,City,State,Zipcode,DOB,Gender,HS,HSCity,GraduationDate,GPA,MathScore,VerbalScore,Major,EnrollmentTerm,EnrollmentYear,EnrollmentDecision")] Applicant applicant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicant);
        }

        // GET: Applicants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Applicant applicant = db.Applicants.Find(id);

            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }

        // POST: Applicants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Applicant applicant = db.Applicants.Find(id);
            db.Applicants.Remove(applicant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectII/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectII.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [Route("about-mason")]
        public ActionResult About()
        {
            ViewBag.Message = "Patriots Bold & Brave";

            return View();
        }

        [Route("contact-us")]
        public ActionResult Contact()
        {
            return View();
        }
    }
}

ProjectII/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Mason";
    ViewBag.Active = "About";
}
<h2 class="text-center text-uppercase">@ViewBag.Message</h2>
<br />
<p>
    George Mason University (Mason, GMU, or George Mason) is a public research university located in Fairfax County near Fairfax City in Virginia.[8] In 1956, the Commonwealth of Virginia authorized the establishment of a Northern Virginia branch of the University of Virginia[9] and the institution that is now named George Mason University opened in September 1957.[10] It became an independent institution in 1972.[1] It has since grown to become the largest four-year public university in the Commonwealth of Virginia. The university is named after the founding father George Mason, a Virginia planter and politician who authored the Virginia Declaration of Rights that later influenced the future Bill of Rights of the United States Constitution. Mason operates four campuses in Virginia (Fairfax, Arlington, Front Royal, and Prince William), as well as a fifth campus in South Korea.
</p>
<br />
<p>
    The university is classified among "R1: Doctoral Universities – Very high research activity".[11] It is particularly well known in the fields of economics and law and economics. Two Mason economics professors have won the Nobel Memorial Prize in Economics: James M. Buchanan in 1986 and Vernon L. Smith in 2002.[12]
</p>
<br /> 
<p>
    EagleBank Arena (formerly the Patriot Center), a 10,000-seat arena and concert venue operated by the university, is located on the main Fairfax campus. The university recognizes 500 student groups as well as 41 fraternities and sororities. <br />
</p>
<br />
<br />
<div class="btn-group btn-group-justified facts" role="group" aria-label="...">
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">
            <span class="icons">$</span>
            <span>
                Avg cost after aid<br />
                <span>$20k</span>
            </span>
        </button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">
            <span class="fas fa-graduation-cap"></span>
            <span>
                Graduation Rate<br /><br />
                <span style="position: relative; top: -5px;">69%</span>
            </span>
        </button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">
            <span class="icons">%</span>
            <span>
                Acceptance Rate<br />
                <span>81%</span>
            </span>
        </button>
    </div>
</div>

ProjectII/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
    ViewBag.Active = "Contact";
}
<h2 class="text-uppercase">@ViewBag.Title</h2>
<br />
<div class="flex-container" style="justify-content: space-between;">
    <address>
        4400 University Drive<br />
        Fairfax, Virginia 22030<br />
        <abbr title="Phone">P:</abbr>
        <a href="tel:7039931000">(703) 993-1000</a>
        <br /><br />
        <p><strong>Admissions Office:</strong>&nbsp;<a href="mailto:admissions@gmu.edu">admissions@gmu.edu</a></p>
        <p><strong>Student Financial Aid:</strong>&nbsp;<a href="mailto:finaid@gmu.edu">finaid@gmu.edu</a></p>
    </address>
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12432.462663254923!2d-77.3073606!3d38.8298118!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd766a653e6557544!2sGeorge%20Mason%20University!5e0!3m2!1sen!2sus!4v1587958861861!5m2!1sen!2sus" width="600" height="400" frameborder="0" style="border:0;" allowfullscreen="true" aria-hidden="false" tabindex="0"></iframe>
</div>
<br /><br />

ProjectII/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
    ViewBag.Active = "Home";
}

<div class="jumbotron">
    <h1>A Campus That's a Cut Above</h1>
    <p class="lead">Mason's Fairfax location, our original campus, is the principal center for undergraduate studies, with residence halls that house more than 6,000 of our 37,000-plus students.</p> 
    <div style="text-align:center">
        @if (!Request.IsAuthenticated)
        {
            <a href="@Url.Action("Create", "Applicants")" class="btn btn-success" id="apply">Apply Now</a>
        }
    </div>
</div>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="~/Content/images/slide5.jpg" alt="mason1">
        </div>

        <div class="item">
            <img src="~/Content/images/slide2.jpg" alt="mason2">
        </div>

        <div class="item">
            <img src="~/Content/images/slide4.jpg" alt="mason3">
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<br /><br />
<div class="row color">
    <div class="col-md-4">
        <h2>Fairfax Campus</h2>
        <p>
            The campus, on 677 wooded acres within 25 minutes of downtown Washington, D.C., offers academic programs in nine colleges and schools.
        </p>
        <p><a class="btn btn-default" href="https://www2.gmu.edu/about-mason/location-fairfax-campus">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Arlington Campus</h2>
        <p>Mason's Arlington Campus, in the Virginia Square neighborhood of Arlington County near Washington, D.C., focuses on graduate and professional programs​. Working adults can advance in their current professions or chart a new career course.</p>
        <p><a class="btn btn-default" href="https://www2.gmu.edu/about-mason/location-arlington-campus">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Science and Technology Campus</h2>
        <p>Mason's Science and Technology Campus in Manassas is in Innovation Park, the largest research business park in Northern Virginia, home to technology companies and government agencies conducting cutting-edge research. It's also the site of the Hylton Performing Arts Center..</p>
        <p><a class="btn btn-default" href="https://www2.gmu.edu/about-mason/location-sci-tech-campus">Learn more &raquo;</a></p>
    </div>
</div>

@section Scripts {
    <script>
    

    </script>
}